source 'https://github.com/CocoaPods/Specs.git'

target 'LFAdTableViewController', :exclusive => true do
  pod "LFAdTableViewController", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "LFAdTableViewController", :path => "../"

  
end
